export const Doctors = [
  {
    name: "Dr. Maya Kulkarni",
    img: "doctors/DrMaya.jpg",
    field: ["Obst. & Gynaecology"],
    rating: 4,
  },
  {
    name: "Dr. Rameshwari Allahabade",
    img: "doctors/DrRameshwari.jpg",
    field: ["Obst. & Gynaecology"],
    rating: 4,
  },
  {
    name: "Dr. Prachi Ruikar",
    img: "doctors/DrPrachi.jpg",
    field: ["Obst. & Gynaecology"],
    rating: 4,
  },
  {
    name: "Dr. Rajashree Gundwar",
    img: "doctors/DrRajashree.jpg",
    field: ["Obst. & Gynaecology"],
    rating: 4,
  },
  {
    name: "Dr. Vaishali Tekale",
    img: "doctors/DrVaishali.jpg",
    field: ["Obst. & Gynaecology", "Infertility Care"],
    rating: 3,
  },
  {
    name: "Dr. Anuja Kulkarni",
    img: "doctors/DrAnuja.jpg",
    field: ["Obst. & Gynaecology", "Infertility Care"],
    rating: 4,
  },
  {
    name: "Dr. Vishvas Kulkarni",
    img: "doctors/DrVishvas.png",
    field: ["Urology", "Infertility Care"],
    rating: 4,
  },
  {
    name: "Dr. Amol Londhe",
    img: "doctors/DrAmol.jpg",
    field: ["Urology"],
    rating: 4,
  },
  {
    name: "Dr. Nitin Sasturkar",
    img: "doctors/DrNitin.jpg",
    field: ["Orthopedics"],
    rating: 4,
  },
  {
    name: "Dr Mahesh Kulkarni",
    img: "doctors/DrMahesh.png",
    field: ["Orthopedics"],
    rating: 3,
  },
  {
    name: "Dr. Ram Kulkarni",
    img: "doctors/DrRam.jpg",
    field: ["Pathology"],
    rating: 4,
  },
  {
    name: "Dr. Amit Utikar",
    img: "doctors/DrAmit.jpg",
    field: ["Radiology"],
    rating: 4,
  },
  {
    name: "Dr. Avinash Kurdukar",
    img: "doctors/DrAvinash.jpg",
    field: ["Radiology"],
    rating: 4,
  },
];
